CREATE TABLE IF NOT EXISTS `Tag`(
id INT NOT NULL AUTO_INCREMENT,
tagname VARCHAR(50) NOT NULL,
createtime DATETIME NOT NULL,
PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS `Article`(
id INT NOT NULL AUTO_INCREMENT,
title VARCHAR(100) NOT NULL,
content TEXT NOT NULL,
brief TEXT NOT NULL,
cover TEXT NOT NULL,
click INT NOT NULL DEFAULT 0,
time DATETIME NOT NULL,
PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS `Article_Tag`(
id INT NOT NULL AUTO_INCREMENT,
article_id INT NOT NULL,
tag_id INT NOT NULL,
PRIMARY KEY(id),
FOREIGN KEY(article_id) REFERENCES Article(id) ON DELETE CASCADE,
FOREIGN KEY(Tag_id) REFERENCES Tag(id)
);

